SELECT * FROM DEPARTMENTS;


SELECT DEPARTMENT_ID
	  ,DEPARTMENT_NAME
	  ,0 AS PARENT_ID
	  ,1 AS LEVELS
	  ,PARENT_ID || DEPARTMENT_ID AS SORT
  FROM DEPARTMENTS d 
WHERE PARENT_ID IS NULL 
	UNION ALL
SELECT T2.DEPARTMENT_ID 
	  ,LPAD(' ' , 3 *(2-1)) || T2.DEPARTMENT_NAME AS DEPARTMENT_NAME
	  ,T2.PARENT_ID
	  ,2 AS LEVELS
	  , T2.PARENT_ID || T2.DEPARTMENT_ID AS  SORT
  FROM DEPARTMENTS T1,
  	   DEPARTMENTS T2
WHERE T1.PARENT_ID IS  NULL 
  AND T2.PARENT_ID = T1.DEPARTMENT_ID
UNION ALL
 SELECT T3.DEPARTMENT_ID
 	   ,LPAD(' ' , 3 *(3-1)) || T3.DEPARTMENT_NAME AS DEPARTMENT_NAME
 	   ,T3.PARENT_ID
 	   ,3 AS  LEVELS
 	   ,T2.PARENT_ID || T3.PARENT_ID || T3.DEPARTMENT_ID  AS SORT
  FROM DEPARTMENTS T1
   	  ,DEPARTMENTS T2
   	  ,DEPARTMENTS T3
 WHERE T1.PARENT_ID IS NULL
 AND T2.PARENT_ID = T1.DEPARTMENT_ID 
 AND T3.PARENT_ID = T2.DEPARTMENT_ID 
UNION ALL 
SELECT T4.DEPARTMENT_ID
	  ,LPAD(' ', 3 *(4-1)) || T4.DEPARTMENT_NAME AS  DEPARTMENT_NAME
	  ,T4.PARENT_ID
	  ,4 AS LEVELS
	  ,T2.PARENT_ID || T3.PARENT_ID || T4.PARENT_ID || T4.DEPARTMENT_ID AS SORT
  FROM DEPARTMENTS T1
  	  ,DEPARTMENTS T2
  	  ,DEPARTMENTS T3
  	  ,DEPARTMENTS T4
WHERE T1.PARENT_ID IS NULL 
  AND T2.PARENT_ID = T1.DEPARTMENT_ID 
  AND T3.DEPARTMENT_ID = T2.DEPARTMENT_ID 
  AND T4.DEPARTMENT_ID = T3.DEPARTMENT_ID 
ORDER BY SORT;